#pragma once

// #define WS2812_DI_PIN B5

// #define RGBLIGHT_HUE_STEP 8
// #define RGBLIGHT_SAT_STEP 8

#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_GRB
#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 50

// #define RGBLIGHT_LED_COUNT 15

// // #define RGBLIGHT_ANIMATIONS

// #define RGBLIGHT_MODE_RGB_TEST 
// #define RGBLIGHT_MODE_BREATHING


// #undef RGBLIGHT_EFFECT_STATIC_GRADIENT
// #undef RGBLIGHT_EFFECT_RAINBOW_SWIRL

